apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-microservice
  namespace: pricing-service
  labels:
    app: pricing-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pricing-microservice
  template:
    metadata:
      labels:
        app: pricing-microservice
        
    spec:
      containers:
      - name: pricing-microservice
        image: shadh/pricing-microservice:latest        
        ports:
        - containerPort: 8080
        
